import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Bun + Next.js + React Three Fiber",
  description: "Generated by bun create next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-900">
        {children}
      </body>
    </html>
  );
}
